---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: kargo-api-pass-raw
  namespace: kargo
spec:
  length: 32
  allowRepeat: false
  noUpper: false
  digits: 10
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: kargo-api-signing-raw
  namespace: kargo
spec:
  length: 32
  allowRepeat: false
  noUpper: false
  digits: 10
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-api-secrets
  namespace: kargo
spec:
  refreshInterval: "0"          # generate once; don't rotate on every sync
  target:
    name: kargo-api-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_ACCOUNT_PASSWORD_HASH: '{{ htpasswd "" .rawPassword | trimPrefix ":" }}'
        ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: '{{ .signingKey }}'
        ADMIN_ACCOUNT_PASSWORD: '{{ .rawPassword }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: kargo-api-pass-raw
      rewrite:
        - regexp:
            source: "password"
            target: "rawPassword"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: kargo-api-signing-raw
      rewrite:
        - regexp:
            source: "password"
            target: "signingKey"