apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: baseappset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/bbomar-reveal/pub
          revision: HEAD
          directories:
          - path: base/autoinstall/*/helm/
  template:
    metadata:
      name: '{{.name}}-{{.path.basename}}'
    spec:
      project: default
      destination:
        namespace: '{{.path.basename}}'
        server: '{{.server}}'
      source:
        repoURL: https://github.com/bbomar-reveal/pub
        targetRevision: HEAD
        path: 'base/autoinstall/{{.path.basename}}/helm/'
        helm:
          parameters:
            - name: domainName
              value: "cluster3"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m